#!/usr/bin/env python3
"""
Reconstruction Test: Parse a known-good K2Node Extras blob into raw values,
then reconstruct it byte-for-byte using the writer.

This proves the parser and writer are perfectly symmetric.
"""
import sys
import struct
import io

sys.path.insert(0, '/home/ubuntu/ue56-level-editor')
sys.path.insert(0, '/home/ubuntu/ue56-level-editor/core')

from parse_extras import ExtrasParser
from k2node_writer import ExtrasWriter


def reconstruct_from_parsed(parsed: dict, name_map: list, owning_export_idx: int,
                            node_class: str, raw_extras: bytes) -> bytes:
    """
    Take parsed output and reconstruct the Extras blob using the writer.
    Uses raw int values from the parser to avoid any resolution issues.
    """
    w = ExtrasWriter(name_map)
    w.stream = io.BytesIO()

    pins = parsed['pins']

    # --- Pin array header ---
    w.write_int32(parsed['num_pins'])

    for pin in pins:
        if pin is None:
            w.write_int32(1)  # bNullPtr = true
            continue

        # SerializePin wrapper: bNullPtr=false, OwningNode, PinGuid
        w.write_int32(0)  # bNullPtr = false
        w.write_int32(pin['_wrapper_owning_node'])  # raw FPackageIndex
        w.write_guid(pin['_wrapper_pin_guid'])

        # --- Pin.Serialize() ---
        # OwningNode (FPackageIndex)
        w.write_int32(pin['OwningNode'])

        # PinId (FGuid)
        w.write_guid(pin['PinId'])

        # PinName (FName) - raw (index, number) tuple
        pn_idx, pn_num = pin['PinName']
        w.write_int32(pn_idx)
        w.write_int32(pn_num)

        # PinFriendlyName (FText) - write raw
        _write_ftext_raw(w, pin['PinFriendlyName'])

        # SourceIndex (int32)
        w.write_int32(pin['SourceIndex'])

        # PinToolTip (FString)
        w.write_fstring(pin['PinToolTip'])

        # Direction (uint8)
        w.write_uint8(pin['Direction'])

        # PinType - all FNames are raw (index, number) tuples
        pt = pin['PinType']
        # PinCategory (FName)
        w.write_int32(pt['PinCategory'][0])
        w.write_int32(pt['PinCategory'][1])
        # PinSubCategory (FName)
        w.write_int32(pt['PinSubCategory'][0])
        w.write_int32(pt['PinSubCategory'][1])
        # PinSubCategoryObject (FPackageIndex) - raw int
        w.write_int32(pt['PinSubCategoryObject'])
        # ContainerType (uint8)
        w.write_uint8(pt['ContainerType'])
        # PinValueType (if Map)
        if pt['ContainerType'] == 4:
            vt = pt['PinValueType']
            w.write_int32(vt['Category'][0])
            w.write_int32(vt['Category'][1])
            w.write_int32(vt['SubCategory'][0])
            w.write_int32(vt['SubCategory'][1])
            w.write_int32(vt['Object'])
            w.write_int32(1 if vt['bIsWeakPointer'] else 0)
        # bIsReference
        w.write_int32(1 if pt['bIsReference'] else 0)
        # bIsWeakPointer
        w.write_int32(1 if pt['bIsWeakPointer'] else 0)
        # FSimpleMemberReference
        w.write_int32(pt['MemberParent'])  # raw FPackageIndex
        w.write_int32(pt['MemberName'][0])
        w.write_int32(pt['MemberName'][1])
        w.write_guid(pt['MemberGuid'])
        # bIsConst
        w.write_int32(1 if pt['bIsConst'] else 0)
        # bIsUObjectWrapper
        w.write_int32(1 if pt['bIsUObjectWrapper'] else 0)
        # bSerializeAsSinglePrecisionFloat
        w.write_int32(1 if pt['bSerializeAsSinglePrecisionFloat'] else 0)

        # DefaultValue (FString)
        w.write_fstring(pin['DefaultValue'])

        # AutogeneratedDefaultValue (FString)
        w.write_fstring(pin['AutogeneratedDefaultValue'])

        # DefaultObject (FPackageIndex) - raw int
        w.write_int32(pin['DefaultObject'])

        # DefaultTextValue (FText) - raw
        _write_ftext_raw(w, pin['DefaultTextValue'])

        # LinkedTo array
        linked = pin['LinkedTo']
        # Count non-null entries
        non_null = [l for l in linked if not l.get('_is_null', False)]
        w.write_int32(len(linked))
        for lt in linked:
            if lt.get('_is_null', False):
                w.write_int32(1)  # bNullPtr = true
            else:
                w.write_int32(0)  # bNullPtr = false
                w.write_int32(lt['OwningNode'])  # raw FPackageIndex
                w.write_guid(lt['PinGuid'])

        # SubPins array
        sub_pins = pin['SubPins']
        w.write_int32(len(sub_pins))
        for sp in sub_pins:
            if sp.get('_is_null', False):
                w.write_int32(1)
            else:
                w.write_int32(0)
                w.write_int32(sp['OwningNode'])
                w.write_guid(sp['PinGuid'])

        # ParentPin
        pp = pin['ParentPin']
        if pp.get('_is_null', False):
            w.write_int32(1)
        else:
            w.write_int32(0)
            w.write_int32(pp['OwningNode'])
            w.write_guid(pp['PinGuid'])

        # RefPassThrough
        rpt = pin['RefPassThrough']
        if rpt.get('_is_null', False):
            w.write_int32(1)
        else:
            w.write_int32(0)
            w.write_int32(rpt['OwningNode'])
            w.write_guid(rpt['PinGuid'])

        # PersistentGuid (FGuid)
        w.write_guid(pin['PersistentGuid'])

        # BitField (uint32)
        w.write_uint32(pin['BitField'])

    return w.get_bytes()


def _resolve_fname(name: str, name_map: list) -> int:
    """Resolve an FName string to its index in the name map."""
    if name in name_map:
        return name_map.index(name)
    # Try without _N suffix (FName number handling)
    # The parser already resolved the full name, so this shouldn't happen
    raise ValueError(f"Name '{name}' not found in name map (size={len(name_map)})")


def _write_ftext_raw(w: ExtrasWriter, ftext: dict):
    """Write an FText from the raw parsed dict."""
    w.write_uint32(ftext['_flags'])
    w.stream.write(struct.pack('<b', ftext['_history_type']))

    ht = ftext['_history_type']
    if ht == -1:
        w.write_int32(ftext.get('_has_culture_invariant', 0))
        if ftext.get('_has_culture_invariant', 0):
            w.write_fstring(ftext['_text'])
    elif ht == 0:
        w.write_fstring(ftext['_namespace'])
        w.write_fstring(ftext['_key'])
        w.write_fstring(ftext['_source'])
    elif ht == 11:
        # StringTableEntry - table_id is raw FName tuple
        tid_idx, tid_num = ftext['_table_id']
        w.write_int32(tid_idx)
        w.write_int32(tid_num)
        w.write_fstring(ftext['_table_key'])


def main():
    """Run reconstruction test on all K2Nodes in the clean Trailer Logic map."""
    # Initialize pythonnet
    import pythonnet
    pythonnet.load("coreclr")
    import clr
    import os
    dll_path = os.path.join('/home/ubuntu/ue56-level-editor', 'lib', 'publish')
    clr.AddReference(os.path.join(dll_path, 'UAssetAPI'))
    from UAssetAPI import UAsset
    from UAssetAPI.UnrealTypes import EngineVersion

    # Load the clean Trailer Logic map
    test_file = '/home/ubuntu/test_assets/SL_Trailer_Logic.umap'
    asset = UAsset(test_file, EngineVersion.VER_UE5_4)

    # Build name map
    name_map = []
    for i in range(asset.GetNameMapIndexList().Count):
        name_map.append(str(asset.GetNameMapIndexList()[i]))

    # Find all K2Node exports
    k2_exports = []
    for i in range(asset.Exports.Count):
        exp = asset.Exports[i]
        class_idx = exp.ClassIndex
        if hasattr(class_idx, 'Index') and class_idx.Index < 0:
            imp_idx = -class_idx.Index - 1
            if imp_idx < asset.Imports.Count:
                imp = asset.Imports[imp_idx]
                cname = str(imp.ObjectName)
                if 'K2Node' in cname:
                    extras = bytes(exp.Extras) if exp.Extras is not None else b''
                    if len(extras) > 0:
                        k2_exports.append((i, cname, extras))

    print(f"Found {len(k2_exports)} K2Nodes with Extras")
    print()

    passed = 0
    failed = 0

    for exp_idx, cname, raw_extras in k2_exports:
        # Parse
        parser = ExtrasParser(raw_extras, name_map)
        parsed = parser.parse()

        # Reconstruct pin portion only (subclass extras handled separately)
        reconstructed = reconstruct_from_parsed(parsed, name_map, exp_idx, cname, raw_extras)

        # Compare up to the pin portion (bytes_consumed from parser)
        pin_bytes = parsed['bytes_consumed']
        original_pins = raw_extras[:pin_bytes]
        recon_pins = reconstructed[:len(reconstructed)]

        if original_pins == recon_pins:
            passed += 1
            status = "PASS"
        else:
            failed += 1
            status = "FAIL"
            # Find first diff
            for j in range(min(len(original_pins), len(recon_pins))):
                if original_pins[j] != recon_pins[j]:
                    print(f"  First diff at byte {j}: orig=0x{original_pins[j]:02X} recon=0x{recon_pins[j]:02X}")
                    # Show context
                    start = max(0, j - 4)
                    end = min(len(original_pins), j + 8)
                    print(f"  Orig [{start}:{end}]: {original_pins[start:end].hex()}")
                    print(f"  Rcon [{start}:{end}]: {recon_pins[start:end].hex()}")
                    break
            if len(original_pins) != len(recon_pins):
                print(f"  Size mismatch: orig={len(original_pins)} recon={len(recon_pins)}")

        exp_name = str(asset.Exports[exp_idx].ObjectName)
        print(f"  [{status}] Export[{exp_idx}] {cname} ({exp_name}): "
              f"orig_pins={len(original_pins)}B recon={len(recon_pins)}B")

    print()
    print(f"Results: {passed} passed, {failed} failed out of {passed + failed}")


if __name__ == '__main__':
    main()
