#!/usr/bin/env python3
"""
Parse a K2Node Extras blob byte-by-byte using the confirmed UE 5.4 serialization format.
Source: EdGraphPin.cpp from //UE5/5.4.4-release

The Extras blob contains everything serialized by UEdGraphNode::Serialize()
AFTER Super::Serialize(Ar) -- i.e., the pin array data.

Format (OwningNode path):
  int32 NumPins
  for each pin:
    SerializePin -> bool bNull, UObject* OwningNode, FGuid PinGuid, then Pin.Serialize()

Pin.Serialize():
  UObject* OwningNode (FPackageIndex int32)
  FGuid PinId (16 bytes)
  FName PinName (int32 index + int32 number)
  FText PinFriendlyName (editor-only)
  int32 SourceIndex (UE5 only)
  FString PinToolTip
  uint8 Direction
  FEdGraphPinType PinType
  FString DefaultValue
  FString AutogeneratedDefaultValue
  UObject* DefaultObject (FPackageIndex int32)
  FText DefaultTextValue
  LinkedTo array
  SubPins array
  ParentPin
  ReferencePassThroughConnection
  FGuid PersistentGuid (editor-only)
  uint32 BitField (editor-only)
"""

import sys, struct, io

sys.path.insert(0, '/home/ubuntu/ue56-level-editor')
from core.uasset_bridge import AssetFile


class ExtrasParser:
    """Parse K2Node Extras blobs using the confirmed UE 5.4 format."""

    def __init__(self, data: bytes, name_map: list, asset_file=None):
        self.stream = io.BytesIO(data)
        self.name_map = name_map
        self.asset = asset_file
        self.total_size = len(data)

    def pos(self):
        return self.stream.tell()

    def remaining(self):
        return self.total_size - self.pos()

    # --- Primitive readers ---

    def read_int32(self):
        return struct.unpack('<i', self.stream.read(4))[0]

    def read_uint32(self):
        return struct.unpack('<I', self.stream.read(4))[0]

    def read_uint8(self):
        return struct.unpack('<B', self.stream.read(1))[0]

    def read_bool(self):
        """UE serializes bool as int32."""
        val = self.read_int32()
        return bool(val)

    def read_guid(self):
        """FGuid: 4 x uint32 (A, B, C, D)."""
        a, b, c, d = struct.unpack('<IIII', self.stream.read(16))
        return f"{a:08X}{b:08X}{c:08X}{d:08X}"

    def read_fname(self):
        """FName: int32 NameIndex + int32 Number. Returns human-readable string."""
        idx = self.read_int32()
        num = self.read_int32()
        if 0 <= idx < len(self.name_map):
            name = self.name_map[idx]
            if num > 0:
                name = f"{name}_{num - 1}"
            return name
        else:
            return f"<INVALID_FNAME idx={idx} num={num}>"

    def read_fname_raw(self):
        """FName: returns raw (index, number) tuple for binary reconstruction."""
        idx = self.read_int32()
        num = self.read_int32()
        return (idx, num)

    def read_fstring(self):
        """FString: int32 length (including null) + chars.
        Negative length = UTF-16.
        Returns None for length=0 (no string), '' for length=1 (empty string)."""
        length = self.read_int32()
        if length == 0:
            return None
        if length < 0:
            # UTF-16
            char_count = -length
            raw = self.stream.read(char_count * 2)
            return raw.decode('utf-16-le').rstrip('\0')
        else:
            raw = self.stream.read(length)
            return raw.decode('utf-8', errors='replace').rstrip('\0')

    def read_ftext(self):
        """FText serialization. Returns raw structured dict for binary reconstruction."""
        flags = self.read_uint32()
        history_type = struct.unpack('<b', self.stream.read(1))[0]

        result = {'_flags': flags, '_history_type': history_type}

        if history_type == -1:
            # HISTORYTYPE_NONE: int32 bHasCultureInvariant, then optional FString
            has_culture_invariant = self.read_int32()
            result['_has_culture_invariant'] = has_culture_invariant
            if has_culture_invariant:
                result['_text'] = self.read_fstring()
        elif history_type == 0:
            # HISTORYTYPE_BASE: namespace + key + source string
            result['_namespace'] = self.read_fstring()
            result['_key'] = self.read_fstring()
            result['_source'] = self.read_fstring()
        elif history_type == 11:
            # HISTORYTYPE_STRINGTABLEENTRY
            result['_table_id'] = self.read_fname_raw()  # raw (index, number) tuple
            result['_table_key'] = self.read_fstring()

        return result

    def read_package_index(self, raw=False):
        """FPackageIndex: int32. Positive=export+1, negative=import, 0=null.
        If raw=True, returns the raw int32 value."""
        idx = self.read_int32()
        if raw:
            return idx
        if idx > 0:
            return f"Export[{idx - 1}]"
        elif idx < 0:
            return f"Import[{-idx - 1}]"
        else:
            return "None"

    def read_package_index_raw(self):
        """FPackageIndex: returns raw int32 for binary reconstruction."""
        return self.read_int32()

    # --- Pin type ---

    def read_pin_type(self):
        """FEdGraphPinType::Serialize. Returns raw values for reconstruction."""
        pin_category = self.read_fname_raw()
        pin_subcategory = self.read_fname_raw()
        pin_subcategory_object_raw = self.read_package_index_raw()
        container_type = self.read_uint8()

        pin_value_type = None
        if container_type == 4:  # Map
            pin_value_type = self.read_terminal_type_raw()

        is_reference = self.read_bool()
        is_weak_pointer = self.read_bool()

        # FSimpleMemberReference
        member_parent_raw = self.read_package_index_raw()
        member_name = self.read_fname_raw()
        member_guid = self.read_guid()

        is_const = self.read_bool()
        is_uobject_wrapper = self.read_bool()
        serialize_single_precision = self.read_bool()

        return {
            'PinCategory': pin_category,
            'PinSubCategory': pin_subcategory,
            'PinSubCategoryObject': pin_subcategory_object_raw,
            'ContainerType': container_type,
            'PinValueType': pin_value_type,
            'bIsReference': is_reference,
            'bIsWeakPointer': is_weak_pointer,
            'MemberParent': member_parent_raw,
            'MemberName': member_name,
            'MemberGuid': member_guid,
            'bIsConst': is_const,
            'bIsUObjectWrapper': is_uobject_wrapper,
            'bSerializeAsSinglePrecisionFloat': serialize_single_precision,
        }

    def read_terminal_type(self):
        """FEdGraphTerminalType"""
        category = self.read_fname()
        subcategory = self.read_fname()
        obj = self.read_package_index()
        is_weak = self.read_bool()
        return {'Category': category, 'SubCategory': subcategory, 'Object': obj, 'bIsWeakPointer': is_weak}

    def read_terminal_type_raw(self):
        """FEdGraphTerminalType with raw values."""
        category = self.read_fname_raw()
        subcategory = self.read_fname_raw()
        obj = self.read_package_index_raw()
        is_weak = self.read_bool()
        return {'Category': category, 'SubCategory': subcategory, 'Object': obj, 'bIsWeakPointer': is_weak}

    # --- Pin reference (for LinkedTo, SubPins, ParentPin) ---

    def read_pin_ref(self, label=""):
        """SerializePin for non-OwningNode paths (LinkedTo, SubPins, ParentPin).
        Returns raw int values for binary reconstruction."""
        is_null_raw = self.read_int32()  # bNullPtr as raw int32
        if is_null_raw:
            return {'_is_null': True}
        owning_node_raw = self.read_package_index_raw()
        pin_guid = self.read_guid()
        return {'_is_null': False, 'OwningNode': owning_node_raw, 'PinGuid': pin_guid}

    def read_pin_ref_array(self, label=""):
        """SerializePinArray for LinkedTo/SubPins."""
        count = self.read_int32()
        refs = []
        for i in range(count):
            ref = self.read_pin_ref(f"{label}[{i}]")
            refs.append(ref)
        return refs

    # --- Full pin ---

    def read_pin(self):
        """UEdGraphPin::Serialize - the full per-pin data."""
        start_pos = self.pos()

        owning_node_raw = self.read_package_index_raw()
        pin_id = self.read_guid()
        pin_name = self.read_fname_raw()
        pin_friendly_name = self.read_ftext()
        source_index = self.read_int32()
        pin_tooltip = self.read_fstring()
        direction = self.read_uint8()
        pin_type = self.read_pin_type()
        default_value = self.read_fstring()
        autogenerated_default_value = self.read_fstring()
        default_object_raw = self.read_package_index_raw()
        default_text_value = self.read_ftext()

        linked_to = self.read_pin_ref_array("LinkedTo")
        sub_pins = self.read_pin_ref_array("SubPins")
        parent_pin = self.read_pin_ref("ParentPin")
        ref_pass_through = self.read_pin_ref("RefPassThrough")

        persistent_guid = self.read_guid()
        bitfield = self.read_uint32()

        end_pos = self.pos()

        return {
            'OwningNode': owning_node_raw,
            'PinId': pin_id,
            'PinName': pin_name,
            'PinFriendlyName': pin_friendly_name,
            'SourceIndex': source_index,
            'PinToolTip': pin_tooltip,
            'Direction': direction,
            'PinType': pin_type,
            'DefaultValue': default_value,
            'AutogeneratedDefaultValue': autogenerated_default_value,
            'DefaultObject': default_object_raw,
            'DefaultTextValue': default_text_value,
            'LinkedTo': linked_to,
            'SubPins': sub_pins,
            'ParentPin': parent_pin,
            'RefPassThrough': ref_pass_through,
            'PersistentGuid': persistent_guid,
            'BitField': bitfield,
            '_bytes': end_pos - start_pos,
        }

    # --- Top-level parse ---

    def parse(self):
        """Parse the full Extras blob."""
        # SerializePinArray (OwningNode path)
        num_pins = self.read_int32()
        pins = []

        for i in range(num_pins):
            # SerializePin wrapper
            is_null = self.read_bool()
            if is_null:
                pins.append(None)
                continue

            # OwningNode + PinGuid (from SerializePin wrapper)
            wrapper_owning_node_raw = self.read_package_index_raw()
            wrapper_pin_guid = self.read_guid()

            # Then the actual Pin.Serialize()
            pin = self.read_pin()
            pin['_wrapper_owning_node'] = wrapper_owning_node_raw
            pin['_wrapper_pin_guid'] = wrapper_pin_guid
            pins.append(pin)

        return {
            'num_pins': num_pins,
            'pins': pins,
            'bytes_consumed': self.pos(),
            'bytes_remaining': self.remaining(),
        }


def main():
    # Load the clean SL_Trailer_Logic.umap
    af = AssetFile("/home/ubuntu/test_assets/SL_Trailer_Logic.umap", "5.6")

    # Build name map list
    name_map = []
    for i in range(af.asset.GetNameMapIndexList().Count):
        name_map.append(str(af.asset.GetNameMapIndexList()[i]))

    # Parse K2Node_CustomEvent_0 (export 67) - 726 bytes
    exp = af.get_export(67)
    extras = bytes(exp.Extras)
    print(f"Parsing export 67: {af.get_export_name(exp)} ({af.get_export_class_name(exp)})")
    print(f"Extras size: {len(extras)} bytes")
    print()

    parser = ExtrasParser(extras, name_map, af)
    try:
        result = parser.parse()
        print(f"Pins: {result['num_pins']}")
        print(f"Bytes consumed: {result['bytes_consumed']}/{len(extras)}")
        print(f"Bytes remaining: {result['bytes_remaining']}")
        print()

        for i, pin in enumerate(result['pins']):
            if pin is None:
                print(f"  Pin[{i}]: NULL")
                continue
            print(f"  Pin[{i}]: {pin['PinName']}")
            print(f"    Direction: {pin['Direction']}")
            print(f"    PinId: {pin['PinId']}")
            print(f"    PinType: {pin['PinType']['PinCategory']}")
            print(f"    DefaultValue: {pin['DefaultValue']!r}")
            print(f"    LinkedTo: {len(pin['LinkedTo'])} connections")
            for lt in pin['LinkedTo']:
                if lt:
                    print(f"      -> {lt['OwningNode']} pin {lt['PinGuid']}")
            print(f"    BitField: {pin['BitField']}")
            print(f"    Bytes: {pin['_bytes']}")
            print()

    except Exception as e:
        print(f"PARSE ERROR at offset {parser.pos()}: {e}")
        import traceback
        traceback.print_exc()
        # Show hex around the error
        pos = parser.pos()
        start = max(0, pos - 16)
        end = min(len(extras), pos + 16)
        print(f"Hex around offset {pos}:")
        print(extras[start:end].hex(' '))


if __name__ == '__main__':
    main()
